# Generated by Django 4.1.3 on 2022-12-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_hotel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
