# Generated by Django 4.2.4 on 2023-11-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='uid',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
